### ISSUE TITLE
Allow variable in include

### ISSUE THREAD

**Issue by mrksbnch** [tnhu/jekyll-include-absolute-plugin#1]
I tried to use a variable in the `include_absolute` path, but it doesn't seem to work.

```
{% include_absolute {{ path }}.html %}
```

This is already supported in Jekyll's build-in `include` and `include_relative` functions.

**Comment by liquidvisual** [comment]
+1

**Comment by bradfrost** [comment]
+1 

This works fantastic for hard coding file names, but I'm dynamically including a bunch of files from an outside directory. My markup looks pretty much exactly like @mrksbnch's.

**Comment by tnhu** [comment]
Hey sorry everyone for being late, I'll look into this issue some time this weekend :)

**Comment by ChrisJefferson** [comment]
Based on random cutting+pasting, I found putting `@file = context[@file] || @file` as the first line of `render` fixes this (I have no idea at all what I did, just cut from another plugin)

**Comment by tnhu** [comment]
Fixed with https://github.com/tnhu/jekyll-include-absolute-plugin/commit/a87f625f0fd9aaeec5d3fcdbaf899f4b307a9d40. Thanks all!
