### ISSUE TITLE
Include params

### ISSUE THREAD

**Issue by inigomedina** [tnhu/jekyll-include-absolute-plugin#3]
Hi,

I'm trying to use your plugin with multiple params like:

`{% include_absolute path item="static" %}`

and it's throwing a parsing error, since it understands `params` as file too:

`Liquid Exception: No such file or directory @ rb_sysope...`

 Do you know how could I get that?

**Comment by maartenbrakkee** [comment]
I've refactored the plugin, re-based it on the original include plugin from Jekyll to add support for parameters. See pull request #4.

Better late than never ;)

**Comment by tnhu** [comment]
Thanks @maartenbrakkee, closing this ticket
