### ISSUE TITLE
Ruby 2.7 warning of using the last argument as keyword parameters

### ISSUE THREAD

**Issue by Soptq** [tnhu/jekyll-include-absolute-plugin#7]
Line 150 causes a warning of using the last argument as keyword parameters in ruby 2.7 and will raise an error in ruby 3.0.

```ruby
def read_file(file, context)
    File.read(file, file_read_opts(context))
end
```

Will make a PR to address this issue very soon.

**Comment by Soptq** [comment]
https://github.com/tnhu/jekyll-include-absolute-plugin/blob/master/include_absolute.rb#L150

**Comment by tnhu** [comment]
Thanks @Soptq, I don't actively use Jekyll anymore so won't have an environment to test the change. Could you make sure the proposed change work under Ruby 2.x as well?
